version: 0.1

phases:
  install:
    commands:
      - echo Installing Node 20...
      - curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
      - yum install -y nodejs
      - echo Installing Yarn...
      - curl -o- -L https://yarnpkg.com/install.sh | bash
      - apt install --no-install-recommends yarn
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn
  build:
    commands:
      - echo Building...
      - yarn build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build

